language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.0"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.1"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
    - php: "7.2"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "nightly"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "master"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=0
    - php: "hhvm"
      os: linux
      env: USE_PSALM=1
           CHECK_MBSTRING=1
  allow_failures:
    - php: "master"
    - php: "hhvm"

install:
    - composer self-update
    - if [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:dev-1.x|dev-master"; fi
    - composer update

script:
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm --debug-by-line; fi
